# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envData.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='envData.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\renvData.proto\"\x19\n\nAgentIndex\x12\x0b\n\x03idx\x18\x01 \x01(\x05\"R\n\x10\x41gentObservation\x12\x18\n\x10ObservationValue\x18\x01 \x01(\x05\x12\x11\n\tAgentPosX\x18\x02 \x01(\x05\x12\x11\n\tAgentPosY\x18\x03 \x01(\x05\"\x0f\n\rUpdateCommand\"\x0e\n\x0cUpdateResult\"!\n\x0bStepCommand\x12\x12\n\naction_idx\x18\x01 \x01(\x05\".\n\nStepResult\x12\x0e\n\x06reward\x18\x01 \x01(\x02\x12\x10\n\x08terminal\x18\x02 \x01(\x08\"\x0e\n\x0cResetCommand\"\r\n\x0bResetResult2\xb7\x01\n\tSimulator\x12\x32\n\x0egetObservation\x12\x0b.AgentIndex\x1a\x11.AgentObservation\"\x00\x12)\n\x06render\x12\x0e.UpdateCommand\x1a\r.UpdateResult\"\x00\x12#\n\x04step\x12\x0c.StepCommand\x1a\x0b.StepResult\"\x00\x12&\n\x05reset\x12\r.ResetCommand\x1a\x0c.ResetResult\"\x00\x62\x06proto3'
)




_AGENTINDEX = _descriptor.Descriptor(
  name='AgentIndex',
  full_name='AgentIndex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idx', full_name='AgentIndex.idx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=42,
)


_AGENTOBSERVATION = _descriptor.Descriptor(
  name='AgentObservation',
  full_name='AgentObservation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ObservationValue', full_name='AgentObservation.ObservationValue', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AgentPosX', full_name='AgentObservation.AgentPosX', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AgentPosY', full_name='AgentObservation.AgentPosY', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=126,
)


_UPDATECOMMAND = _descriptor.Descriptor(
  name='UpdateCommand',
  full_name='UpdateCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=143,
)


_UPDATERESULT = _descriptor.Descriptor(
  name='UpdateResult',
  full_name='UpdateResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=159,
)


_STEPCOMMAND = _descriptor.Descriptor(
  name='StepCommand',
  full_name='StepCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action_idx', full_name='StepCommand.action_idx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=194,
)


_STEPRESULT = _descriptor.Descriptor(
  name='StepResult',
  full_name='StepResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reward', full_name='StepResult.reward', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='terminal', full_name='StepResult.terminal', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=242,
)


_RESETCOMMAND = _descriptor.Descriptor(
  name='ResetCommand',
  full_name='ResetCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=258,
)


_RESETRESULT = _descriptor.Descriptor(
  name='ResetResult',
  full_name='ResetResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=273,
)

DESCRIPTOR.message_types_by_name['AgentIndex'] = _AGENTINDEX
DESCRIPTOR.message_types_by_name['AgentObservation'] = _AGENTOBSERVATION
DESCRIPTOR.message_types_by_name['UpdateCommand'] = _UPDATECOMMAND
DESCRIPTOR.message_types_by_name['UpdateResult'] = _UPDATERESULT
DESCRIPTOR.message_types_by_name['StepCommand'] = _STEPCOMMAND
DESCRIPTOR.message_types_by_name['StepResult'] = _STEPRESULT
DESCRIPTOR.message_types_by_name['ResetCommand'] = _RESETCOMMAND
DESCRIPTOR.message_types_by_name['ResetResult'] = _RESETRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgentIndex = _reflection.GeneratedProtocolMessageType('AgentIndex', (_message.Message,), {
  'DESCRIPTOR' : _AGENTINDEX,
  '__module__' : 'envData_pb2'
  # @@protoc_insertion_point(class_scope:AgentIndex)
  })
_sym_db.RegisterMessage(AgentIndex)

AgentObservation = _reflection.GeneratedProtocolMessageType('AgentObservation', (_message.Message,), {
  'DESCRIPTOR' : _AGENTOBSERVATION,
  '__module__' : 'envData_pb2'
  # @@protoc_insertion_point(class_scope:AgentObservation)
  })
_sym_db.RegisterMessage(AgentObservation)

UpdateCommand = _reflection.GeneratedProtocolMessageType('UpdateCommand', (_message.Message,), {
  'DESCRIPTOR' : _UPDATECOMMAND,
  '__module__' : 'envData_pb2'
  # @@protoc_insertion_point(class_scope:UpdateCommand)
  })
_sym_db.RegisterMessage(UpdateCommand)

UpdateResult = _reflection.GeneratedProtocolMessageType('UpdateResult', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESULT,
  '__module__' : 'envData_pb2'
  # @@protoc_insertion_point(class_scope:UpdateResult)
  })
_sym_db.RegisterMessage(UpdateResult)

StepCommand = _reflection.GeneratedProtocolMessageType('StepCommand', (_message.Message,), {
  'DESCRIPTOR' : _STEPCOMMAND,
  '__module__' : 'envData_pb2'
  # @@protoc_insertion_point(class_scope:StepCommand)
  })
_sym_db.RegisterMessage(StepCommand)

StepResult = _reflection.GeneratedProtocolMessageType('StepResult', (_message.Message,), {
  'DESCRIPTOR' : _STEPRESULT,
  '__module__' : 'envData_pb2'
  # @@protoc_insertion_point(class_scope:StepResult)
  })
_sym_db.RegisterMessage(StepResult)

ResetCommand = _reflection.GeneratedProtocolMessageType('ResetCommand', (_message.Message,), {
  'DESCRIPTOR' : _RESETCOMMAND,
  '__module__' : 'envData_pb2'
  # @@protoc_insertion_point(class_scope:ResetCommand)
  })
_sym_db.RegisterMessage(ResetCommand)

ResetResult = _reflection.GeneratedProtocolMessageType('ResetResult', (_message.Message,), {
  'DESCRIPTOR' : _RESETRESULT,
  '__module__' : 'envData_pb2'
  # @@protoc_insertion_point(class_scope:ResetResult)
  })
_sym_db.RegisterMessage(ResetResult)



_SIMULATOR = _descriptor.ServiceDescriptor(
  name='Simulator',
  full_name='Simulator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=276,
  serialized_end=459,
  methods=[
  _descriptor.MethodDescriptor(
    name='getObservation',
    full_name='Simulator.getObservation',
    index=0,
    containing_service=None,
    input_type=_AGENTINDEX,
    output_type=_AGENTOBSERVATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='render',
    full_name='Simulator.render',
    index=1,
    containing_service=None,
    input_type=_UPDATECOMMAND,
    output_type=_UPDATERESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='step',
    full_name='Simulator.step',
    index=2,
    containing_service=None,
    input_type=_STEPCOMMAND,
    output_type=_STEPRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='reset',
    full_name='Simulator.reset',
    index=3,
    containing_service=None,
    input_type=_RESETCOMMAND,
    output_type=_RESETRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMULATOR)

DESCRIPTOR.services_by_name['Simulator'] = _SIMULATOR

# @@protoc_insertion_point(module_scope)
