# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import envData_pb2 as envData__pb2


class SimulatorStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getObservation = channel.unary_unary(
                '/Simulator/getObservation',
                request_serializer=envData__pb2.AgentIndex.SerializeToString,
                response_deserializer=envData__pb2.AgentObservation.FromString,
                )
        self.render = channel.unary_unary(
                '/Simulator/render',
                request_serializer=envData__pb2.UpdateCommand.SerializeToString,
                response_deserializer=envData__pb2.UpdateResult.FromString,
                )
        self.step = channel.unary_unary(
                '/Simulator/step',
                request_serializer=envData__pb2.StepCommand.SerializeToString,
                response_deserializer=envData__pb2.StepResult.FromString,
                )
        self.reset = channel.unary_unary(
                '/Simulator/reset',
                request_serializer=envData__pb2.ResetCommand.SerializeToString,
                response_deserializer=envData__pb2.ResetResult.FromString,
                )


class SimulatorServicer(object):
    """Missing associated documentation comment in .proto file"""

    def getObservation(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def render(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def step(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reset(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getObservation': grpc.unary_unary_rpc_method_handler(
                    servicer.getObservation,
                    request_deserializer=envData__pb2.AgentIndex.FromString,
                    response_serializer=envData__pb2.AgentObservation.SerializeToString,
            ),
            'render': grpc.unary_unary_rpc_method_handler(
                    servicer.render,
                    request_deserializer=envData__pb2.UpdateCommand.FromString,
                    response_serializer=envData__pb2.UpdateResult.SerializeToString,
            ),
            'step': grpc.unary_unary_rpc_method_handler(
                    servicer.step,
                    request_deserializer=envData__pb2.StepCommand.FromString,
                    response_serializer=envData__pb2.StepResult.SerializeToString,
            ),
            'reset': grpc.unary_unary_rpc_method_handler(
                    servicer.reset,
                    request_deserializer=envData__pb2.ResetCommand.FromString,
                    response_serializer=envData__pb2.ResetResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Simulator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Simulator(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def getObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Simulator/getObservation',
            envData__pb2.AgentIndex.SerializeToString,
            envData__pb2.AgentObservation.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def render(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Simulator/render',
            envData__pb2.UpdateCommand.SerializeToString,
            envData__pb2.UpdateResult.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Simulator/step',
            envData__pb2.StepCommand.SerializeToString,
            envData__pb2.StepResult.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Simulator/reset',
            envData__pb2.ResetCommand.SerializeToString,
            envData__pb2.ResetResult.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
